FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY common/ ./common/
COPY notification-service/ ./
ENV OTEL_SERVICE_NAME=notification-service
CMD opentelemetry-instrument --traces_exporter otlp_proto_http --metrics_exporter none --logs_exporter none uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}
